version: '3.6'
services:
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    networks:
      - guacamole_internal_network
    restart: always
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    depends_on: 
      - guacd
      - guacamole_db
    hostname: guacamole.ndser.page
    restart: always
    networks:
      - traefik_proxy
      - guacamole_internal_network
    volumes:
      - ../config/guacamole-extensions:/guac_home/extensions
    environment:
      GUACAMOLE_HOME: /guac_home
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: guacamole_db
      POSTGRES_PASSWORD: ${GUACAMOLE_SQL_PASSWORD:-guacdb}
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
    links:
      - guacd
      - guacamole_db
    labels:
      - traefik.http.routers.guacamole.rule=Host(`guacamole.ndser.page`)
      - traefik.http.routers.guacamole.entrypoints=https
      - traefik.http.routers.guacamole.tls=true
      - traefik.http.routers.guacamole.tls.certresolver=letsencrypt
      - traefik.http.services.guacamole.loadbalancer.server.port=8080
  guacamole_db:
    image: postgres
    container_name: guacamole_db
    restart: always
    networks:
      - guacamole_internal_network
    volumes:
      - ../config/guacamole_db_init:/docker-entrypoint-initdb.d:ro
      - ~/.guacamole/db:/var/lib/postgresql/data:rw
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_PASSWORD: ${GUACAMOLE_SQL_PASSWORD:-guacdb}
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user

networks:
  guacamole_internal_network:
    driver: bridge
  traefik_proxy:
    external:
      name: traefik_proxy
