version: "3.3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus.ndser.page
    networks:
      - traefik_proxy
    restart: unless-stopped
    volumes:
      - ~/.dockerServices/prometheus/data:/prometheus
      - ~/.dockerServices/prometheus/config:/etc/prometheus
    labels:
      - traefik.http.routers.prometheus.rule=Host(`prometheus.ndser.page`)
      - traefik.http.routers.prometheus.entrypoints=https
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=letsencrypt
      - traefik.http.services.prometheus.loadbalancer.server.port=9090

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
