version: "3.3"
services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    hostname: splunk.ndser.page
    networks:
      - traefik_proxy
    environment: 
     - SPLUNK_PASSWORD=basicPaSS
     - SPLUNK_START_ARGS=--accept-license
    labels:
      - traefik.http.routers.splunk.rule=Host(`splunk.ndser.page`)
      - traefik.http.routers.splunk.entrypoints=https
      - traefik.http.routers.splunk.tls=true
      - traefik.http.routers.splunk.tls.certresolver=letsencrypt
      - traefik.http.services.splunk.loadbalancer.server.port=8000

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
